// <auto-generated />
using System;
using MediaPark.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MediaPark.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210530153105_CreatingRelationshipBetweenDayAndHoliday")]
    partial class CreatingRelationshipBetweenDayAndHoliday
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MediaPark.Entities.Country", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryCode");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("MediaPark.Entities.Country_HolidayType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HolidayTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("HolidayTypeId");

                    b.ToTable("Country_HolidayTypes");
                });

            modelBuilder.Entity("MediaPark.Entities.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DayOfTheMonth")
                        .HasColumnType("int");

                    b.Property<string>("DayStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HolidayId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("MediaPark.Entities.FromDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode")
                        .IsUnique()
                        .HasFilter("[CountryCode] IS NOT NULL");

                    b.ToTable("FromDates");
                });

            modelBuilder.Entity("MediaPark.Entities.FullYearOfHolidays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.ToTable("FullYearOfHolidays");
                });

            modelBuilder.Entity("MediaPark.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfTheWeek")
                        .HasColumnType("int");

                    b.Property<int>("HolidayTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("DayId")
                        .IsUnique();

                    b.HasIndex("HolidayTypeId");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("MediaPark.Entities.HolidayName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HolidayId")
                        .HasColumnType("int");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HolidayId");

                    b.ToTable("HolidayNames");
                });

            modelBuilder.Entity("MediaPark.Entities.HolidayType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HolidayTypes");
                });

            modelBuilder.Entity("MediaPark.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("MediaPark.Entities.ToDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode")
                        .IsUnique()
                        .HasFilter("[CountryCode] IS NOT NULL");

                    b.ToTable("ToDates");
                });

            modelBuilder.Entity("MediaPark.Entities.Country_HolidayType", b =>
                {
                    b.HasOne("MediaPark.Entities.Country", "Country")
                        .WithMany("Country_HolidayTypes")
                        .HasForeignKey("CountryCode");

                    b.HasOne("MediaPark.Entities.HolidayType", "HolidayType")
                        .WithMany("Country_HolidayTypes")
                        .HasForeignKey("HolidayTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("HolidayType");
                });

            modelBuilder.Entity("MediaPark.Entities.FromDate", b =>
                {
                    b.HasOne("MediaPark.Entities.Country", "Country")
                        .WithOne("FromDate")
                        .HasForeignKey("MediaPark.Entities.FromDate", "CountryCode");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MediaPark.Entities.FullYearOfHolidays", b =>
                {
                    b.HasOne("MediaPark.Entities.Country", "Country")
                        .WithMany("FullYearOfHolidays")
                        .HasForeignKey("CountryCode");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MediaPark.Entities.Holiday", b =>
                {
                    b.HasOne("MediaPark.Entities.Country", "Country")
                        .WithMany("Holiday")
                        .HasForeignKey("CountryCode");

                    b.HasOne("MediaPark.Entities.Day", "Day")
                        .WithOne("Holiday")
                        .HasForeignKey("MediaPark.Entities.Holiday", "DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaPark.Entities.HolidayType", "HolidayType")
                        .WithMany("Holiday")
                        .HasForeignKey("HolidayTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Day");

                    b.Navigation("HolidayType");
                });

            modelBuilder.Entity("MediaPark.Entities.HolidayName", b =>
                {
                    b.HasOne("MediaPark.Entities.Holiday", "Holiday")
                        .WithMany("HolidayName")
                        .HasForeignKey("HolidayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holiday");
                });

            modelBuilder.Entity("MediaPark.Entities.Region", b =>
                {
                    b.HasOne("MediaPark.Entities.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryCode");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MediaPark.Entities.ToDate", b =>
                {
                    b.HasOne("MediaPark.Entities.Country", "Country")
                        .WithOne("ToDate")
                        .HasForeignKey("MediaPark.Entities.ToDate", "CountryCode");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MediaPark.Entities.Country", b =>
                {
                    b.Navigation("Country_HolidayTypes");

                    b.Navigation("FromDate");

                    b.Navigation("FullYearOfHolidays");

                    b.Navigation("Holiday");

                    b.Navigation("Regions");

                    b.Navigation("ToDate");
                });

            modelBuilder.Entity("MediaPark.Entities.Day", b =>
                {
                    b.Navigation("Holiday");
                });

            modelBuilder.Entity("MediaPark.Entities.Holiday", b =>
                {
                    b.Navigation("HolidayName");
                });

            modelBuilder.Entity("MediaPark.Entities.HolidayType", b =>
                {
                    b.Navigation("Country_HolidayTypes");

                    b.Navigation("Holiday");
                });
#pragma warning restore 612, 618
        }
    }
}
